# Site settings
title: blog
email: evan.wingfield@me.com
description: > # this means to ignore newlines until "baseurl:"
  Photos, travel, programming, and maybe a stray thought or two. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evandavis.me" # the base hostname & protocol for your site
twitter_username: wahoo
github_username:  evanwdavis
exclude: [_daily-photos/new_photos.rb]

collections:
  - daily-photos

permalink: date

# Google Analytics
google_analytics: UA-107130571-1

# Build settings
markdown: kramdown
