# Site settings
title: pictures and words
email: evan.wingfield@me.com
description: > # this means to ignore newlines until "baseurl:"
  Photos, travel, programming, and maybe a stray thought or two. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evanwdavis.github.io" # the base hostname & protocol for your site
twitter_username: wahoo
github_username:  evanwdavis

collections:
  - daily-photos

# Build settings
markdown: kramdown
